processor:
  batch-size: 50000
  absolute-dump-directory: C:\ProgramData\MySQL\MySQL Server 8.3\Uploads\

spring:
  cloud:
    stream:
      function:
        bindings:
          elaborateCsv-in-0: input
          elaborateCsv-out-0: output
      bindings:
        input:
          destination: csvdump
        output:
          destination: filedump
  datasource:
    url: jdbc:mysql://localhost:3306/csv_ingestion
    username: root
    password: 1234